
            .section     .irom0.literal, "ax", @progbits

            .section     .text, "ax", @progbits

            .section     .data, "aw", @progbits

.Ldata001:  .byte        0x0c, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00
            .word        0x00000000                            #   14: 00000000
            .byte        0xe8, 0x03, 0x00, 0x00, 0x00, 0x00, 0x82, 0x00
            .byte        0x3a, 0x01, 0x3a, 0x01, 0x00, 0x00, 0x00, 0x00
            .byte        0xd0, 0x07, 0x00, 0x00, 0x04, 0x01, 0x84, 0x01
            .byte        0x02, 0x01, 0xa2, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x7c, 0x15, 0x00, 0x00, 0x04, 0x02, 0x8b, 0x02
            .byte        0xdf, 0x00, 0x7f, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0xf8, 0x2a, 0x00, 0x00, 0x04, 0x03, 0x96, 0x03
            .byte        0xd5, 0x00, 0x75, 0x00, 0x01, 0x00, 0x00, 0x00
            .byte        0x70, 0x17, 0x00, 0x00, 0x00, 0x0b, 0x0c, 0x04
            .byte        0x3c, 0x00, 0x3c, 0x00, 0x01, 0x00, 0x00, 0x00
            .byte        0x28, 0x23, 0x00, 0x00, 0x00, 0x0f, 0x12, 0x04
            .byte        0x3c, 0x00, 0x3c, 0x00, 0x01, 0x00, 0x00, 0x00
            .byte        0xe0, 0x2e, 0x00, 0x00, 0x00, 0x0a, 0x18, 0x06
            .byte        0x30, 0x00, 0x30, 0x00, 0x01, 0x00, 0x00, 0x00
            .byte        0x50, 0x46, 0x00, 0x00, 0x00, 0x0e, 0x24, 0x06
            .byte        0x30, 0x00, 0x30, 0x00, 0x01, 0x00, 0x00, 0x00
            .byte        0xc0, 0x5d, 0x00, 0x00, 0x00, 0x09, 0x30, 0x08
            .byte        0x2c, 0x00, 0x2c, 0x00, 0x01, 0x00, 0x00, 0x00
            .byte        0xa0, 0x8c, 0x00, 0x00, 0x00, 0x0d, 0x48, 0x08
            .byte        0x2c, 0x00, 0x2c, 0x00, 0x01, 0x00, 0x00, 0x00
            .byte        0x80, 0xbb, 0x00, 0x00, 0x00, 0x08, 0x60, 0x08
            .byte        0x2c, 0x00, 0x2c, 0x00, 0x01, 0x00, 0x00, 0x00
            .byte        0xf0, 0xd2, 0x00, 0x00, 0x00, 0x0c, 0x6c, 0x08
            .byte        0x2c, 0x00, 0x2c, 0x00
.Label001:  .byte        0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0xe8, 0x03, 0x00, 0x00, 0x00, 0x00, 0x82, 0x00
            .byte        0x3a, 0x01, 0x3a, 0x01, 0x00, 0x00, 0x00, 0x00
            .byte        0xd0, 0x07, 0x00, 0x00, 0x04, 0x01, 0x84, 0x01
            .byte        0x02, 0x01, 0xa2, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x7c, 0x15, 0x00, 0x00, 0x04, 0x02, 0x8b, 0x01
            .byte        0xdf, 0x00, 0x7f, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0xf8, 0x2a, 0x00, 0x00, 0x04, 0x03, 0x96, 0x01
            .byte        0xd5, 0x00, 0x75, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
            .byte        0x00, 0x00, 0x00, 0x00

            .section     .bss, "aw", @nobits

            .section     .irom0.text, "ax", @progbits

.Lrel001:   .word        .data                                 #    0: 00000000

# Function @ .irom0.text+0x4
.literal_position
sdk_ieee80211_get_11g_ratetable:
            movi         a2, .Lrel001 /* .Ldata001 */          #    4: 21ffff
            ret.n         /* .Ldata001 */                      #    7: 0df0

            .balign      4
.Lrel002:   .word        .Label001                             #    c: d4000000
.Lrel003:   .word        .data                                 #   10: 00000000

# Function @ .irom0.text+0x14
.literal_position
sdk_ieee80211_get_ratetable:
            l32i.n       a2, a2, 0 /* [arg0] */                #   14: 2802
            movi         a3, 192 /* 0x000000c0 */              #   16: 32a0c0
            ball         a2, a3, .Lbr001                       #   19: 37420a
            movi         a4, 1152 /* 0x00000480 */             #   1c: 42a480
            ball         a2, a4, .Lbr001                       #   1f: 474204
            movi         a2, .Lrel002 /* .Label001 */          #   22: 21faff
            ret.n         /* .Label001 */                      #   25: 0df0
.Lbr001:    movi         a2, .Lrel003 /* .Ldata001 */          #   27: 21faff
            ret.n         /* .Ldata001 */                      #   2a: 0df0

.Lrel004:   .word        sdk_g_ic                              #   2c: 00000000

# Function @ .irom0.text+0x30
# Local variables/stack:
#     (local0):  word      @ -0x10
#     (local1):  word[3]   @ -0xc
.literal_position
sdk_ieee80211_phy_init:
            addi         a1, a1, -16 /* (local0) */            #   30: 12c1f0
            s32i.n       a12, a1, 4 /* a12 -> [(local1)] */    #   33: c911
            s32i.n       a0, a1, 0 /* a0 -> [(local0)] */      #   35: 0901
            mov.n        a12, a2 /* arg0 */                    #   37: cd02
            call0        sdk_ieee80211_setup_ratetable         #   39: 050000
            movi.n       a3, 12 /* 0x0000000c */               #   3c: 0cc3
            movi.n       a0, 3 /* 0x00000003 */                #   3e: 0c30
            movi.n       a5, 4 /* 0x00000004 */                #   40: 0c45
            movi         a2, .Lrel004 /* sdk_g_ic */           #   42: 21faff
            addi.n       a4, a12, -1 /* arg0-0x1 */            #   45: 0b4c
            movi.n       a6, 0 /* 0x00000000 */                #   47: 0c06
            l32i.n       a12, a1, 4 /* [(local1)] */           #   49: c811
            s8i          a6, a2, 125 /* 0x00 -> [sdk_g_ic+0x7d] */ #   4b: 62427d
            s8i          a6, a2, 126 /* 0x00 -> [sdk_g_ic+0x7e] */ #   4e: 62427e
            s8i          a5, a2, 127 /* 0x04 -> [sdk_g_ic+0x7f] */ #   51: 52427f
            movnez       a0, a3, a4                            #   54: 400393
            s8i          a0, a2, 124 /* a0 -> [sdk_g_ic+0x7c] */ #   57: 02427c
            l32i.n       a0, a1, 0 /* [(local0)] */            #   5a: 0801
            addi         a1, a1, 16 /* (top of frame) */       #   5c: 12c110
            ret.n         /* sdk_g_ic */                       #   5f: 0df0

            .balign      4
.Lrel005:   .word        sdk_g_ic+0x200                        #   64: 00000000

# Function @ .irom0.text+0x68
.literal_position
sdk_ieee80211_phy_type_get:
            movi         a2, .Lrel005 /* sdk_g_ic+0x200 */     #   68: 21ffff
            l32i         a2, a2, 0x31c /* [sdk_g_ic+0x51c] */  #   6b: 2222c7
            movi.n       a3, 1 /* 0x00000001 */                #   6e: 0c13
            addi.n       a2, a2, -1 /* [sdk_g_ic+0x51c]-0x1 */ #   70: 0b22
            movnez       a2, a3, a2                            #   72: 202393
            ret.n                                              #   75: 0df0

            .balign      4
.Lrel006:   .word        .data                                 #   78: 00000000
.Lrel007:   .word        .Label001                             #   7c: d4000000
.Lrel008:   .word        sdk_g_ic                              #   80: 00000000

# Function @ .irom0.text+0x84
.literal_position
sdk_ieee80211_setup_ratetable:
            movi         a4, .Lrel006 /* .Ldata001 */          #   84: 41fdff
            movi         a5, .Lrel007 /* .Label001 */          #   87: 51fdff
            addi.n       a6, a2, -1 /* arg0-0x1 */             #   8a: 0b62
            movnez       a5, a4, a6                            #   8c: 605493
            movi         a6, .Lrel008 /* sdk_g_ic */           #   8f: 61fcff
            l8ui         a3, a5, 0                             #   92: 320500
            s8i          a3, a6, 44 /* a3 -> [sdk_g_ic+0x2c] */ #   95: 32462c
            beqz.n       a3, .Lbr003                           #   98: 9c83
            movi.n       a2, 0 /* 0x00000000 */                #   9a: 0c02
.Lbr002:    add.n        a4, a2, a6                            #   9c: 6a42
            slli         a3, a2, 4                             #   9e: c03211
            add.n        a3, a5, a3                            #   a1: 3a35
            addi.n       a2, a2, 1                             #   a3: 1b22
            l8ui         a3, a3, 30                            #   a5: 32031e
            s8i          a3, a4, 45                            #   a8: 32442d
            l8ui         a7, a6, 44 /* [sdk_g_ic+0x2c] */      #   ab: 72062c
            extui        a2, a2, 0, 8                          #   ae: 202074
            bltu         a2, a7, .Lbr002                       #   b1: 7732e7
.Lbr003:    ret.n                                              #   b4: 0df0

            .balign      4
.Lrel009:   .word        __udivsi3                             #   b8: 00000000
.Lrel010:   .word        __udivsi3                             #   bc: 00000000
.Lrel011:   .word        __udivsi3                             #   c0: 00000000

# Function @ .irom0.text+0xc4
# Local variables/stack:
#     (local0):  word      @ -0x10
#     (local1):  word      @ -0xc
#     (local2):  word[2]   @ -0x8
.literal_position
sdk_ieee80211_compute_duration:
            addi         a1, a1, -16 /* (local0) */            #   c4: 12c1f0
            s32i.n       a0, a1, 8 /* a0 -> [(local2)] */      #   c7: 0921
            add.n        a0, a4, a2                            #   c9: 2a04
            l8ui         a0, a0, 4                             #   cb: 020004
            mov.n        a7, a3 /* arg1 */                     #   ce: 7d03
            slli         a0, a0, 4                             #   d0: c00011
            add.n        a0, a2, a0                            #   d3: 0a02
            l32i.n       a3, a0, 24                            #   d5: 3860
            l8ui         a2, a0, 20                            #   d7: 220014
            bnez.n       a3, .Lbr004                           #   da: cc33
            movi.n       a2, 0 /* 0x00000000 */                #   dc: 0c02
            j            .Lbr008                               #   de: 061400
.Lbr004:    s32i.n       a7, a1, 4 /* arg1 -> [(local1)] */    #   e1: 7911
            beqz.n       a2, .Lbr005                           #   e3: ac52
            bnei         a2, 1, .Lbr007                        #   e5: 661246
            slli         a2, a3, 2                             #   e8: e02311
            movi         a3, 1000 /* 0x000003e8 */             #   eb: 32a3e8
            movi         a0, .Lrel009 /* __udivsi3 */          #   ee: 01f2ff
            callx0       a0 /* __udivsi3 */                    #   f1: c00000
            mov.n        a3, a2                                #   f4: 3d02
            l32i.n       a2, a1, 4 /* [(local1)] */            #   f6: 2811
            addx8        a2, a2, a3                            #   f8: 3022b0
            addi         a2, a2, 21                            #   fb: 22c215
            movi         a0, .Lrel010 /* __udivsi3 */          #   fe: 01efff
            callx0       a0 /* __udivsi3 */                    #  101: c00000
            movi.n       a0, 36 /* 0x00000024 */               #  104: 2c40
            addx4        a0, a2, a0                            #  106: 0002a0
            j            .Lbr007                               #  109: 860800
.Lbr005:    beqz.n       a5, .Lbr009                           #  10c: ac95
            l8ui         a2, a0, 28                            #  10e: 22001c
            movi         a4, 96 /* 0x00000060 */               #  111: 42a060
            beqz.n       a2, .Lbr009                           #  114: ac12
            s32i.n       a4, a1, 0 /* 0x00000060 -> [(local0)] */ #  116: 4901
.Lbr006:    l32i.n       a2, a1, 4 /* [(local1)] */            #  118: 2811
            movi         a4, 1000 /* 0x000003e8 */             #  11a: 42a3e8
            slli         a2, a2, 3                             #  11d: d02211
            mull         a2, a2, a4                            #  120: 402282
            movi         a0, .Lrel011 /* __udivsi3 */          #  123: 01e7ff
            callx0       a0 /* __udivsi3 */                    #  126: c00000
            l32i.n       a0, a1, 0 /* [(local0)] */            #  129: 0801
            add.n        a0, a0, a2                            #  12b: 2a00
            addi.n       a0, a0, 10                            #  12d: ab00
.Lbr007:    extui        a2, a0, 0, 16                         #  12f: 0020f4
.Lbr008:    l32i.n       a0, a1, 8 /* [(local2)] */            #  132: 0821
            addi         a1, a1, 16 /* (top of frame) */       #  134: 12c110
            ret.n                                              #  137: 0df0
.Lbr009:    movi         a2, 192 /* 0x000000c0 */              #  139: 22a0c0
            s32i.n       a2, a1, 0 /* 0x000000c0 -> [(local0)] */ #  13c: 2901
            j            .Lbr006                               #  13e: 86f5ff

            .balign      4
.Lrel012:   .word        .data                                 #  144: 00000000

# Function @ .irom0.text+0x148
.literal_position
sdk_ieee80211_dot11Rate_rix:
            movi.n       a6, 0 /* 0x00000000 */                #  148: 0c06
            movi         a8, .Lrel012 /* .Ldata001 */          #  14a: 81feff
.Lbr010:    slli         a7, a6, 4                             #  14d: c07611
            add.n        a7, a8, a7                            #  150: 7a78
            l8ui         a4, a7, 30                            #  152: 42071e
            bne          a4, a2, .Lbr011                       #  155: 279409
            mov.n        a2, a6                                #  158: 2d06
            l8ui         a8, a7, 29                            #  15a: 82071d
            s8i          a8, a3, 0 /* a8 -> [arg1] */          #  15d: 824300
            ret.n                                              #  160: 0df0
.Lbr011:    addi.n       a6, a6, 1                             #  162: 1b66
            extui        a6, a6, 0, 8                          #  164: 606074
            bnei         a6, 12, .Lbr010                       #  167: 66a6e2
            movi         a2, 255 /* 0x000000ff */              #  16a: 22a0ff
            ret.n         /* 0x000000ff */                     #  16d: 0df0
